### ISSUE TITLE
getaddrinfo ENOTFOUND bajor.omegle.com

### ISSUE THREAD

**Issue by alexbinary** [CRogers/omegle#8]
```javascript
const Omegle = require('omegle').Omegle

var omegleClient = new Omegle()

omegleClient.start((err) => {
  if (err) {
    console.error(err)
  }
})
```

```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND bajor.omegle.com bajor.omegle.com:80
    at errnoException (dns.js:53:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:95:26)
```

```
$ dig bajor.omegle.com

; <<>> DiG 9.8.3-P1 <<>> bajor.omegle.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20916
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;bajor.omegle.com.              IN      A

;; AUTHORITY SECTION:
omegle.com.             1863    IN      SOA     gene.ns.cloudflare.com. dns.cloudflare.com. 2025475919 10000 2400 604800 3600

;; Query time: 29 msec
;; SERVER: 192.168.1.16#53(192.168.1.16)
;; WHEN: Wed Sep 20 20:28:16 2017
;; MSG SIZE  rcvd: 93
```

Anyone knows if this might just be a temporary issue or if something is broken ?

### Edit

https://github.com/ash47/OmegleMiddleMan says :

    Original omegle client was taken from here [https://github.com/CRogers/omegle], it no longer works as the protocol has mostly changed.

This answers that.

**Comment by CRogers** [comment]
Yeah, I wrote this many years ago and have no idea if it still works. Happy to accept fixes.
